# Default values for automation-toolbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ansibleGen:
  image: dstoffel/ansible-gen
  #tag:
  pullPolicy: IfNotPresent

ansible:
  image: dstoffel/ansible
  #tag:
  pullPolicy: IfNotPresent

terraformGen:
  image: dstoffel/terraform-gen
  #tag:
  pullPolicy: IfNotPresent

terraform:
  image: dstoffel/terraform
  #tag:
  pullPolicy: IfNotPresent

operator:
  image:  dstoffel/terraform-operator
  pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    annotations: {}
    name: ""

ui:
  enabled: true
  replicas: 1
  image: dstoffel/ui
  secret: default_secret
  #tag:
  pullPolicy: IfNotPresent
  users: [{"username": "admin", "password" : "password"}]
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  ingress:
    enabled: false
    host: chart-example.local
    tlsSecret: ""
  serviceLB:
    enabled: true
    port: 80

  service:
    type: ClusterIP
    port: 80

states:
  defaultCustomTerraformInit: ""
  defaultTerraformOption: ""
  defaultTrustedCA: ""

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
