{{- if  .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terraform-ui
  annotations:
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if  .Values.ui.ingress.tlsSecret }}
  tls:
  - hosts:
    - "{{ .Values.ui.ingress.host }}"
    secretName: "{{.Values.ui.ingress.tlsSecret }}"
{{- end }}
  rules:
  - host: "{{ .Values.ui.ingress.host }}"
    http:
      paths:
      - backend:
          service:
            name: terraform-ui
            port:
              name: http
        path: /
        pathType: Prefix
{{- end }}
