{{- if  .Values.ui.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: terraform-ui
spec:
{{- if  .Values.ui.ingress.tlsSecret }}
  tls:
  - hosts:
    - "{{ .Values.ui.ingress.host }}"
    secretName: "{{.Values.ui.ingress.tlsSecret }}"
{{- end }}
  rules:
  - host: "{{ .Values.ui.ingress.host }}"
    http:
      paths:
      - backend:
          serviceName: terraform-ui
          servicePort: http
{{- end }}
