{{- if  .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: terraform-ui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    application: terraform-ui
{{- end }}
---
{{- if  .Values.ui.serviceLB.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: terraform-ui-lb
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.ui.serviceLB.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    application: terraform-ui
{{- end }}
