---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tfgen-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: terraform-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: terraform-operator
  template:
    metadata:
      labels:
        application: terraform-operator
    spec:
      serviceAccountName: terraform-operator
      containers:
      - name: terraform
        image: harbor.pks.lab.platform-essential.com/library/terraform-operator:latest
        imagePullPolicy: Always
