apiVersion: terraform.dst.io/v1
kind: ClusterModuleTemplate
metadata:
  name: svvm
spec:
  defaultAttributes:
  - name: cluster_name
    sValue: VxRail
  - name: datacenter_name
    sValue: Datacenter
  - name: datastore_name
    sValue: VSAN
  - name: dns_servers
    lsValue:
    - 172.19.36.2
  - name: domain
    sValue: vm.lab.platform-essential.com
  - name: folder_path
    sValue: dst
  - name: network_name
    sValue: vm_network
  - name: source
    sValue: git::http://toolbox.vm.lab.platform-essential.com/toolbox-repos/terraform-module-svvm.git
  - name: template_name
    sValue: ubuntu-1804-tpl-davy
  environments:
  - name: dev 
    defaultAttributes:
    - name: folder
      sValue: dst-dev
  requiredAttributes:
  - name: vmnames
    type: lsValue
  - name: num_cpus
    type: iValue
  - name: memory