apiVersion: terraform.dst.io/v1
kind: Module
metadata:
  name: mymod2
  label:
spec:
  autoPlanRequest: false
  clusterModuleTemplate: svvm
  attributes:
    vmnames:
    - dst-tf-k8s2
    num_cpus: 2
    memory: 1024
