name: CI
on:
  #push:
  #  branches: [ dst-op ]
    #  pull_request:
    #    branches: [ master ]
  create:
jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Terraform - Build and push
        uses: docker/build-push-action@v2
        with:
          context: images/terraform/
          push: true
          tags: dstoffel/terraform:${GITHUB_REF/refs\/tags\//}

     