name: CI
on:
  #push:
  #  branches: [ dst-op ]
    #  pull_request:
    #    branches: [ master ]
  create:
jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: terraform
        run: docker build images/terraform -t terraform:${GITHUB_REF/refs\/tags\//}
      - name: terraform-gen
        run: docker build images/terraform-gen -t terraform-gen:${GITHUB_REF/refs\/tags\//}
      - name: ansible
        run: docker build images/ansible -t ansible:${GITHUB_REF/refs\/tags\//}
      - name: ansible-gen
        run: docker build images/ansible -t ansible-gen:${GITHUB_REF/refs\/tags\//}
      - name: terraform-operator
        run: docker build images/terraform-operator -t terraform-operator:${GITHUB_REF/refs\/tags\//}
      - name: list
        run: docker images
