name: CI
on:
  #push:
  #  branches: [ dst-op ]
    #  pull_request:
    #    branches: [ master ]
  create:
jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build images/terraform -t terraform:${GITHUB_REF/refs\/tags\//}
      - name: list
        run: docker images
