name: CI
on:
  #push:
  #  branches: [ dst-op ]
    #  pull_request:
    #    branches: [ master ]
  create:
jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/*' ]]; then
            TAGS=${GITHUB_REF/refs\/tags\//}
          else
            TAGS = "latest"
           echo '::set-output name=tags::'$TAGS
      - name: Terraform - Build and push
        uses: docker/build-push-action@v2
        with:
          context: images/terraform/
          push: true
          tags: dstoffel/terraform:${{ steps.gen_tags.outputs.tags }}

     