name: CI
on:
  #push:
  #  branches: [ dst-op ]
    #  pull_request:
    #    branches: [ master ]
  create:
jobs:
  build:
    #if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: aze
        run: ls -l $GITHUB_WORKSPACE
      - name: env
        run: env
